<?php
/**
 *                    Jojo CMS
 *                ================
 *
 * Copyright 2007-2008 Harvey Kane <code@ragepank.com>
 * Copyright 2007-2008 Michael Holt <code@gardyneholt.co.nz>
 * Copyright 2007 Melanie Schulz <mel@gardyneholt.co.nz>
 *
 * See the enclosed file license.txt for license information (LGPL). If you
 * did not receive this file, see http://www.fsf.org/copyleft/lgpl.html.
 *
 * @author  Harvey Kane <code@ragepank.com>
 * @author  Michael Cochrane <mikec@jojocms.org>
 * @author  Melanie Schulz <mel@gardyneholt.co.nz>
 * @license http://www.fsf.org/copyleft/lgpl.html GNU Lesser General Public License
 * @link    http://www.jojocms.org JojoCMS
 * @package jojo_contact

  These arrays are used to define custom fields for the contact form.

  DO NOT edit this file, as this file will change with futire versions.
  Instead, copy the contents of this file into a new file called "fields.php"
  (in the same directory). Make whatever changes you like to fields.php

  This is a simple 2d array describing the form. Although the output is simple,
  it is clean CSS, has reliable server side validation and basic Javascript
  validation.

  Fields should be defined as follows...

  ++$f;
  $fields[$f]['field'] = 'FirstName';                     //The ID of the field - no spaces, keep it short but descriptive
  $fields[$f]['display'] = 'First Name';                  //The display name - this will show on the form and in the resulting email
  $fields[$f]['displayonly'] = false;                     //This field shows only on the form, not in the email. Use with headings and notes
  $fields[$f]['required'] = true;                         //true or false - is this a required field?
  $fields[$f]['validation'] = '';                         //The type of validation to be used - options are 'email', 'url', 'text', 'integer' or leave blank for no validation.
  $fields[$f]['type'] = 'text';                           //type of input - use 'text', 'textarea', 'checkboxes', 'heading', 'note' - more options to come
  $fields[$f]['size'] = 40;                               //Used for 'text' type fields - the size of the input. For headings, is the H size (1=biggest)
  $fields[$f]['value'] = '';                              //A default value if any
  $fields[$f]['options'] = array('option 1','option 2');  //An array of options. Required for 'checkboxes' type
  $fields[$f]['rows'] = '15';                             //number of rows - only needed for textareas
  $fields[$f]['cols'] = '40';                             //number of columns - only needed for textareas
  $fields[$f]['fieldset'] = 'Contact';                    //Name of fieldset this field belongs to - empty means no fieldset will be used
  $fields[$f]['description'] = 'Foo bar';                 //A short description to be shown below the field, to explain the field to the user
 */
$f=0;
$from_email_field = 'Email';
$from_name_fields = array('FirstName', ' ', 'LastName'); //this is an array of all fields to be used

++$f;
$fields[$f]['field']       = 'FirstName';
$fields[$f]['display']     = 'First Name';
$fields[$f]['required']    = true;
$fields[$f]['validation']  = '';
$fields[$f]['type']        = 'text';
$fields[$f]['size']        = 30;
$fields[$f]['value']       = '';
$fields[$f]['description'] = '';

++$f;
$fields[$f]['field']       = 'LastName';
$fields[$f]['display']     = 'Last Name';
$fields[$f]['required']    = true;
$fields[$f]['validation']  = '';
$fields[$f]['type']        = 'text';
$fields[$f]['size']        = 30;
$fields[$f]['value']       = '';
$fields[$f]['description'] = '';

++$f;
$fields[$f]['field']       = 'Email';
$fields[$f]['display']     = 'Email';
$fields[$f]['required']    = true;
$fields[$f]['validation']  = 'email';
$fields[$f]['type']        = 'text';
$fields[$f]['size']        = 30;
$fields[$f]['value']       = '';
$fields[$f]['description'] = '';

++$f;
$fields[$f]['field']       = 'Message';
$fields[$f]['display']     = 'Message';
$fields[$f]['required']    = true;
$fields[$f]['validation']  = 'text';
$fields[$f]['type']        = 'textarea';
$fields[$f]['rows']        = '15';
$fields[$f]['cols']        = '29';
$fields[$f]['value']       = '';
$fields[$f]['description'] = '';

/*
++$f;
$fields[$f]['field']       = 'Phone';
$fields[$f]['display']     = 'Phone';
$fields[$f]['required']    = false;
$fields[$f]['validation']  = '';
$fields[$f]['type']        = 'text';
$fields[$f]['size']        = 20;
$fields[$f]['value']       = '';
$fields[$f]['description'] = '';
*/